package layers

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/google/uuid"

	"github.com/oleg3190/Web-studio-img/backend/internal/auth"
	"github.com/oleg3190/Web-studio-img/backend/internal/humanactions"
	"github.com/oleg3190/Web-studio-img/backend/internal/provenance"
)

type Layer struct {
	ID uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	UserID uuid.UUID `json:"user_id"`
	IterationID *uuid.UUID `json:"iteration_id,omitempty"`
	AssetID *uuid.UUID `json:"asset_id,omitempty"`
	ParentLayerID *uuid.UUID `json:"parent_layer_id,omitempty"`
	Name string `json:"name"`
	LayerType string `json:"layer_type"`
	OrderIndex int `json:"order_index"`
	Visible bool `json:"visible"`
	Opacity float64 `json:"opacity"`
	BlendMode string `json:"blend_mode"`
	SourceKind string `json:"source_kind"`
	Metadata map[string]any `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ManualEdit struct {
	ID uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	UserID uuid.UUID `json:"user_id"`
	IterationID *uuid.UUID `json:"iteration_id,omitempty"`
	SourceAssetID uuid.UUID `json:"source_asset_id"`
	MaskAssetID *uuid.UUID `json:"mask_asset_id,omitempty"`
	ResultAssetID *uuid.UUID `json:"result_asset_id,omitempty"`
	Operation string `json:"operation"`
	Prompt *string `json:"prompt,omitempty"`
	Parameters map[string]any `json:"parameters"`
	Status string `json:"status"`
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Handler struct{db *sql.DB;actions *humanactions.Store;provenance *provenance.Store}
func NewHandler(db *sql.DB,a *humanactions.Store,p *provenance.Store)(*Handler,error){if db==nil{return nil,errors.New("layers handler requires database")};return &Handler{db:db,actions:a,provenance:p},nil}
func(h *Handler)Register(mux *http.ServeMux){
	mux.HandleFunc("GET /api/v1/projects/{project_id}/layers",h.listLayers)
	mux.HandleFunc("POST /api/v1/projects/{project_id}/layers",h.createLayer)
	mux.HandleFunc("PATCH /api/v1/projects/{project_id}/layers/{layer_id}",h.updateLayer)
	mux.HandleFunc("DELETE /api/v1/projects/{project_id}/layers/{layer_id}",h.deleteLayer)
	mux.HandleFunc("GET /api/v1/projects/{project_id}/manual-edits",h.listEdits)
	mux.HandleFunc("POST /api/v1/projects/{project_id}/manual-edits",h.createEdit)
	mux.HandleFunc("POST /api/v1/projects/{project_id}/manual-edits/{edit_id}/apply",h.applyEdit)
	mux.HandleFunc("POST /api/v1/projects/{project_id}/manual-edits/{edit_id}/reject",h.rejectEdit)
}
type layerInput struct{IterationID *uuid.UUID `json:"iteration_id,omitempty"`;AssetID *uuid.UUID `json:"asset_id,omitempty"`;ParentLayerID *uuid.UUID `json:"parent_layer_id,omitempty"`;Name string `json:"name"`;LayerType string `json:"layer_type"`;OrderIndex int `json:"order_index"`;Visible *bool `json:"visible,omitempty"`;Opacity *float64 `json:"opacity,omitempty"`;BlendMode string `json:"blend_mode"`;SourceKind string `json:"source_kind"`;Metadata map[string]any `json:"metadata,omitempty"`}
type editInput struct{IterationID *uuid.UUID `json:"iteration_id,omitempty"`;SourceAssetID uuid.UUID `json:"source_asset_id"`;MaskAssetID *uuid.UUID `json:"mask_asset_id,omitempty"`;ResultAssetID *uuid.UUID `json:"result_asset_id,omitempty"`;Operation string `json:"operation"`;Prompt *string `json:"prompt,omitempty"`;Parameters map[string]any `json:"parameters,omitempty"`}
func uid(r *http.Request)(uuid.UUID,bool){p,ok:=auth.PrincipalFromContext(r.Context());if !ok{return uuid.Nil,false};return p.UserID,true}
func dec(r *http.Request,v any)error{d:=json.NewDecoder(io.LimitReader(r.Body,1<<20));d.DisallowUnknownFields();if e:=d.Decode(v);e!=nil{return e};var extra any;if e:=d.Decode(&extra);e!=io.EOF{return errors.New("multiple json values")};return nil}
func(h *Handler)ownedProject(ctx context.Context,u,p uuid.UUID)bool{var ok bool;return h.db.QueryRowContext(ctx,`SELECT EXISTS(SELECT 1 FROM projects WHERE id=$1 AND user_id=$2 AND status <> 'deleted')`,p,u).Scan(&ok)==nil&&ok}
func(h *Handler)ownedAsset(ctx context.Context,u,p,id uuid.UUID)bool{var ok bool;return h.db.QueryRowContext(ctx,`SELECT EXISTS(SELECT 1 FROM assets a JOIN projects p ON p.id=a.project_id WHERE a.id=$1 AND a.project_id=$2 AND p.user_id=$3)`,id,p,u).Scan(&ok)==nil&&ok}
func(h *Handler)ownedIteration(ctx context.Context,u,p,id *uuid.UUID)bool{if id==nil{return true};var ok bool;return h.db.QueryRowContext(ctx,`SELECT EXISTS(SELECT 1 FROM iterations i JOIN projects p ON p.id=i.project_id WHERE i.id=$1 AND i.project_id=$2 AND p.user_id=$3)`,*id,p,u).Scan(&ok)==nil&&ok}

func(h *Handler) listLayers(w http.ResponseWriter,r *http.Request){u,ok:=uid(r);if !ok{outErr(w,401,"unauthorized","authentication required");return};p,e:=uuid.Parse(r.PathValue("project_id"));if e!=nil||!h.ownedProject(r.Context(),u,p){outErr(w,404,"project_not_found","project not found");return};rows,e:=h.db.QueryContext(r.Context(),`SELECT id,project_id,user_id,iteration_id,asset_id,parent_layer_id,name,layer_type,order_index,visible,opacity,blend_mode,source_kind,metadata,created_at,updated_at FROM project_layers WHERE project_id=$1 AND user_id=$2 ORDER BY order_index ASC,created_at ASC`,p,u);if e!=nil{outErr(w,500,"layers_list_failed","could not list layers");return};defer rows.Close();out:=[]Layer{};for rows.Next(){var x Layer;var raw []byte;if e:=rows.Scan(&x.ID,&x.ProjectID,&x.UserID,&x.IterationID,&x.AssetID,&x.ParentLayerID,&x.Name,&x.LayerType,&x.OrderIndex,&x.Visible,&x.Opacity,&x.BlendMode,&x.SourceKind,&raw,&x.CreatedAt,&x.UpdatedAt);e!=nil{outErr(w,500,"layers_list_failed","could not read layers");return};_=json.Unmarshal(raw,&x.Metadata);if x.Metadata==nil{x.Metadata=map[string]any{}};out=append(out,x)};write(w,200,map[string]any{"layers":out})}
func(h *Handler)createLayer(w http.ResponseWriter,r *http.Request){u,ok:=uid(r);if !ok{outErr(w,401,"unauthorized","authentication required");return};p,e:=uuid.Parse(r.PathValue("project_id"));if e!=nil||!h.ownedProject(r.Context(),u,p){outErr(w,404,"project_not_found","project not found");return};var in layerInput;if e=dec(r,&in);e!=nil{outErr(w,400,"invalid_request","invalid layer payload");return};if strings.TrimSpace(in.Name)==""||in.LayerType==""||!h.ownedIteration(r.Context(),u,p,in.IterationID){outErr(w,400,"invalid_layer","name/type/iteration are invalid");return};if in.AssetID!=nil&&!h.ownedAsset(r.Context(),u,p,*in.AssetID){outErr(w,400,"invalid_asset","asset is not owned by project");return};if in.ParentLayerID!=nil{var okParent bool;_ = h.db.QueryRowContext(r.Context(),`SELECT EXISTS(SELECT 1 FROM project_layers WHERE id=$1 AND project_id=$2 AND user_id=$3)`,*in.ParentLayerID,p,u).Scan(&okParent);if !okParent{outErr(w,400,"invalid_parent_layer","parent layer is invalid");return}};visible:=true;if in.Visible!=nil{visible=*in.Visible};opacity:=1.0;if in.Opacity!=nil{opacity=*in.Opacity};if opacity<0||opacity>1{outErr(w,400,"invalid_opacity","opacity must be between 0 and 1");return};blend:=strings.TrimSpace(in.BlendMode);if blend==""{blend="normal"};source:=strings.TrimSpace(in.SourceKind);if source==""{source="human"};raw,_:=json.Marshal(in.Metadata);var x Layer;e=h.db.QueryRowContext(r.Context(),`INSERT INTO project_layers(project_id,user_id,iteration_id,asset_id,parent_layer_id,name,layer_type,order_index,visible,opacity,blend_mode,source_kind,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id,project_id,user_id,iteration_id,asset_id,parent_layer_id,name,layer_type,order_index,visible,opacity,blend_mode,source_kind,metadata,created_at,updated_at`,p,u,in.IterationID,in.AssetID,in.ParentLayerID,strings.TrimSpace(in.Name),in.LayerType,in.OrderIndex,visible,opacity,blend,source,raw).Scan(&x.ID,&x.ProjectID,&x.UserID,&x.IterationID,&x.AssetID,&x.ParentLayerID,&x.Name,&x.LayerType,&x.OrderIndex,&x.Visible,&x.Opacity,&x.BlendMode,&x.SourceKind,&raw,&x.CreatedAt,&x.UpdatedAt);if e!=nil{outErr(w,500,"layer_create_failed","could not create layer");return};_=json.Unmarshal(raw,&x.Metadata);h.audit(r,u,p,x.ID,"LAYER_CREATED",map[string]any{"layer_type":x.LayerType,"asset_id":x.AssetID});write(w,201,x)}
func(h *Handler)updateLayer(w http.ResponseWriter,r *http.Request){u,ok:=uid(r);if !ok{outErr(w,401,"unauthorized","authentication required");return};p,e:=uuid.Parse(r.PathValue("project_id"));if e!=nil||!h.ownedProject(r.Context(),u,p){outErr(w,404,"project_not_found","project not found");return};id,e:=uuid.Parse(r.PathValue("layer_id"));if e!=nil{outErr(w,400,"invalid_layer_id","invalid layer id");return};var in layerInput;if e=dec(r,&in);e!=nil{outErr(w,400,"invalid_request","invalid layer payload");return};visible:=true;if in.Visible!=nil{visible=*in.Visible};opacity:=1.0;if in.Opacity!=nil{opacity=*in.Opacity};if in.Name==""{var oldName string;_ = h.db.QueryRowContext(r.Context(),`SELECT name FROM project_layers WHERE id=$1 AND project_id=$2 AND user_id=$3`,id,p,u).Scan(&oldName);in.Name=oldName};if in.LayerType==""{in.LayerType="image"};if in.BlendMode==""{in.BlendMode="normal"};if in.SourceKind==""{in.SourceKind="human"};if !validLayerType(in.LayerType)||!validSourceKind(in.SourceKind){outErr(w,400,"invalid_layer","unsupported layer type or source kind");return};raw,_:=json.Marshal(in.Metadata);var x Layer;e=h.db.QueryRowContext(r.Context(),`UPDATE project_layers SET iteration_id=$1,asset_id=$2,parent_layer_id=$3,name=$4,layer_type=$5,order_index=$6,visible=$7,opacity=$8,blend_mode=$9,source_kind=$10,metadata=COALESCE($11,metadata),updated_at=now() WHERE id=$12 AND project_id=$13 AND user_id=$14 RETURNING id,project_id,user_id,iteration_id,asset_id,parent_layer_id,name,layer_type,order_index,visible,opacity,blend_mode,source_kind,metadata,created_at,updated_at`,in.IterationID,in.AssetID,in.ParentLayerID,strings.TrimSpace(in.Name),in.LayerType,in.OrderIndex,visible,opacity,in.BlendMode,in.SourceKind,raw,id,p,u).Scan(&x.ID,&x.ProjectID,&x.UserID,&x.IterationID,&x.AssetID,&x.ParentLayerID,&x.Name,&x.LayerType,&x.OrderIndex,&x.Visible,&x.Opacity,&x.BlendMode,&x.SourceKind,&raw,&x.CreatedAt,&x.UpdatedAt);if errors.Is(e,sql.ErrNoRows){outErr(w,404,"layer_not_found","layer not found");return};if e!=nil{outErr(w,500,"layer_update_failed","could not update layer");return};_=json.Unmarshal(raw,&x.Metadata);h.audit(r,u,p,x.ID,"LAYER_UPDATED",map[string]any{"layer_id":id});write(w,200,x)}
func(h *Handler)deleteLayer(w http.ResponseWriter,r *http.Request){u,ok:=uid(r);if !ok{outErr(w,401,"unauthorized","authentication required");return};p,e:=uuid.Parse(r.PathValue("project_id"));if e!=nil||!h.ownedProject(r.Context(),u,p){outErr(w,404,"project_not_found","project not found");return};id,e:=uuid.Parse(r.PathValue("layer_id"));if e!=nil{outErr(w,400,"invalid_layer_id","invalid layer id");return};res,e:=h.db.ExecContext(r.Context(),`DELETE FROM project_layers WHERE id=$1 AND project_id=$2 AND user_id=$3`,id,p,u);if e!=nil{outErr(w,500,"layer_delete_failed","could not delete layer");return};n,_:=res.RowsAffected();if n!=1{outErr(w,404,"layer_not_found","layer not found");return};h.audit(r,u,p,id,"LAYER_DELETED",map[string]any{"layer_id":id});w.WriteHeader(http.StatusNoContent)}

func(h *Handler)listEdits(w http.ResponseWriter,r *http.Request){u,ok:=uid(r);if !ok{outErr(w,401,"unauthorized","authentication required");return};p,e:=uuid.Parse(r.PathValue("project_id"));if e!=nil||!h.ownedProject(r.Context(),u,p){outErr(w,404,"project_not_found","project not found");return};rows,e:=h.db.QueryContext(r.Context(),`SELECT id,project_id,user_id,iteration_id,source_asset_id,mask_asset_id,result_asset_id,operation,prompt,parameters,status,idempotency_key,created_at,updated_at FROM manual_edits WHERE project_id=$1 AND user_id=$2 ORDER BY created_at DESC`,p,u);if e!=nil{outErr(w,500,"manual_edits_list_failed","could not list manual edits");return};defer rows.Close();out:=[]ManualEdit{};for rows.Next(){var x ManualEdit;var raw []byte;if e:=rows.Scan(&x.ID,&x.ProjectID,&x.UserID,&x.IterationID,&x.SourceAssetID,&x.MaskAssetID,&x.ResultAssetID,&x.Operation,&x.Prompt,&raw,&x.Status,&x.IdempotencyKey,&x.CreatedAt,&x.UpdatedAt);e!=nil{outErr(w,500,"manual_edits_list_failed","could not read manual edits");return};_=json.Unmarshal(raw,&x.Parameters);if x.Parameters==nil{x.Parameters=map[string]any{}};out=append(out,x)};write(w,200,map[string]any{"edits":out})}
func(h *Handler)createEdit(w http.ResponseWriter,r *http.Request){u,ok:=uid(r);if !ok{outErr(w,401,"unauthorized","authentication required");return};p,e:=uuid.Parse(r.PathValue("project_id"));if e!=nil||!h.ownedProject(r.Context(),u,p){outErr(w,404,"project_not_found","project not found");return};key:=strings.TrimSpace(r.Header.Get("Idempotency-Key"));if key==""||len(key)>200{outErr(w,400,"missing_idempotency_key","Idempotency-Key header is required");return};var in editInput;if e=dec(r,&in);e!=nil{outErr(w,400,"invalid_request","invalid manual edit payload");return};if in.SourceAssetID==uuid.Nil||!h.ownedAsset(r.Context(),u,p,in.SourceAssetID){outErr(w,400,"invalid_source_asset","source asset is not owned by project");return};if in.MaskAssetID!=nil&&!h.ownedAsset(r.Context(),u,p,*in.MaskAssetID){outErr(w,400,"invalid_mask_asset","mask asset is not owned by project");return};if in.ResultAssetID!=nil&&!h.ownedAsset(r.Context(),u,p,*in.ResultAssetID){outErr(w,400,"invalid_result_asset","result asset is not owned by project");return};if !h.ownedIteration(r.Context(),u,p,in.IterationID){outErr(w,400,"invalid_iteration","iteration is not owned by project");return};op:=strings.ToLower(strings.TrimSpace(in.Operation));if op!="paint"&&op!="erase"&&op!="mask"&&op!="composite"{outErr(w,400,"invalid_operation","unsupported manual edit operation");return};params,_:=json.Marshal(in.Parameters);var x ManualEdit;var existing bool
	e=h.db.QueryRowContext(r.Context(),`INSERT INTO manual_edits(project_id,user_id,iteration_id,source_asset_id,mask_asset_id,result_asset_id,operation,prompt,parameters,status,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'draft',$10) ON CONFLICT (user_id,project_id,idempotency_key) DO NOTHING RETURNING id,project_id,user_id,iteration_id,source_asset_id,mask_asset_id,result_asset_id,operation,prompt,parameters,status,idempotency_key,created_at,updated_at`,p,u,in.IterationID,in.SourceAssetID,in.MaskAssetID,in.ResultAssetID,op,in.Prompt,params,key).Scan(&x.ID,&x.ProjectID,&x.UserID,&x.IterationID,&x.SourceAssetID,&x.MaskAssetID,&x.ResultAssetID,&x.Operation,&x.Prompt,&params,&x.Status,&x.IdempotencyKey,&x.CreatedAt,&x.UpdatedAt)
	if errors.Is(e,sql.ErrNoRows){existing=true;e=h.db.QueryRowContext(r.Context(),`SELECT id,project_id,user_id,iteration_id,source_asset_id,mask_asset_id,result_asset_id,operation,prompt,parameters,status,idempotency_key,created_at,updated_at FROM manual_edits WHERE user_id=$1 AND idempotency_key=$2`,u,key).Scan(&x.ID,&x.ProjectID,&x.UserID,&x.IterationID,&x.SourceAssetID,&x.MaskAssetID,&x.ResultAssetID,&x.Operation,&x.Prompt,&params,&x.Status,&x.IdempotencyKey,&x.CreatedAt,&x.UpdatedAt)}
	if e!=nil{outErr(w,500,"manual_edit_create_failed","could not create manual edit");return};_=json.Unmarshal(params,&x.Parameters);if !existing{h.audit(r,u,p,x.ID,"MANUAL_EDIT_CREATED",map[string]any{"edit_id":x.ID,"operation":x.Operation,"source_asset_id":x.SourceAssetID,"mask_asset_id":x.MaskAssetID,"idempotency_key":key})};if x.MaskAssetID!=nil{h.audit(r,u,p,*x.MaskAssetID,"MASK_CREATED",map[string]any{"mask_asset_id":x.MaskAssetID,"source_asset_id":x.SourceAssetID})};write(w,201,x)}
func(h *Handler)applyEdit(w http.ResponseWriter,r *http.Request){u,ok:=uid(r);if !ok{outErr(w,401,"unauthorized","authentication required");return};p,e:=uuid.Parse(r.PathValue("project_id"));if e!=nil||!h.ownedProject(r.Context(),u,p){outErr(w,404,"project_not_found","project not found");return};id,e:=uuid.Parse(r.PathValue("edit_id"));if e!=nil{outErr(w,400,"invalid_edit_id","invalid edit id");return};var resultID *uuid.UUID;var source uuid.UUID;e=h.db.QueryRowContext(r.Context(),`SELECT source_asset_id,result_asset_id,status FROM manual_edits WHERE id=$1 AND project_id=$2 AND user_id=$3`,id,p,u).Scan(&source,&resultID,new(string));if errors.Is(e,sql.ErrNoRows){outErr(w,404,"manual_edit_not_found","manual edit not found");return};if e!=nil{outErr(w,500,"manual_edit_get_failed","could not load manual edit");return};if resultID==nil{outErr(w,409,"result_asset_required","upload and attach the derived result asset before apply");return};var x ManualEdit;var raw []byte;e=h.db.QueryRowContext(r.Context(),`UPDATE manual_edits SET status='applied',updated_at=now() WHERE id=$1 AND project_id=$2 AND user_id=$3 RETURNING id,project_id,user_id,iteration_id,source_asset_id,mask_asset_id,result_asset_id,operation,prompt,parameters,status,created_at,updated_at`,id,p,u).Scan(&x.ID,&x.ProjectID,&x.UserID,&x.IterationID,&x.SourceAssetID,&x.MaskAssetID,&x.ResultAssetID,&x.Operation,&x.Prompt,&raw,&x.Status,&x.CreatedAt,&x.UpdatedAt);if e!=nil{outErr(w,500,"manual_edit_apply_failed","could not apply manual edit");return};_=json.Unmarshal(raw,&x.Parameters);h.audit(r,u,p,x.ID,"MANUAL_EDIT_APPLIED",map[string]any{"edit_id":id,"source_asset_id":source,"result_asset_id":resultID});write(w,200,x)}
func(h *Handler)rejectEdit(w http.ResponseWriter,r *http.Request){u,ok:=uid(r);if !ok{outErr(w,401,"unauthorized","authentication required");return};p,e:=uuid.Parse(r.PathValue("project_id"));if e!=nil||!h.ownedProject(r.Context(),u,p){outErr(w,404,"project_not_found","project not found");return};id,e:=uuid.Parse(r.PathValue("edit_id"));if e!=nil{outErr(w,400,"invalid_edit_id","invalid edit id");return};var x ManualEdit;var raw []byte;e=h.db.QueryRowContext(r.Context(),`UPDATE manual_edits SET status='rejected',updated_at=now() WHERE id=$1 AND project_id=$2 AND user_id=$3 RETURNING id,project_id,user_id,iteration_id,source_asset_id,mask_asset_id,result_asset_id,operation,prompt,parameters,status,created_at,updated_at`,id,p,u).Scan(&x.ID,&x.ProjectID,&x.UserID,&x.IterationID,&x.SourceAssetID,&x.MaskAssetID,&x.ResultAssetID,&x.Operation,&x.Prompt,&raw,&x.Status,&x.CreatedAt,&x.UpdatedAt);if errors.Is(e,sql.ErrNoRows){outErr(w,404,"manual_edit_not_found","manual edit not found");return};if e!=nil{outErr(w,500,"manual_edit_reject_failed","could not reject manual edit");return};_=json.Unmarshal(raw,&x.Parameters);h.audit(r,u,p,x.ID,"MANUAL_EDIT_REJECTED",map[string]any{"edit_id":id});write(w,200,x)}
func(h *Handler)audit(r *http.Request,u,p,id uuid.UUID,a string,payload map[string]any){if h.actions!=nil{_,_=h.actions.Create(r.Context(),u,p,humanactions.Request{ActionType:a,Payload:payload})};if h.provenance!=nil{_,_=h.provenance.Append(r.Context(),provenance.Event{UserID:u,ProjectID:p,EntityType:"layered_editing",EntityID:id,Action:strings.ToLower(a),Payload:payload})}}
func validLayerType(v string) bool { switch v { case "base","mask","image","manual_edit","adjustment","group": return true }; return false }
func validSourceKind(v string) bool { switch v { case "human","ai","derived","imported": return true }; return false }

func write(w http.ResponseWriter,s int,v any){w.Header().Set("Content-Type","application/json");w.WriteHeader(s);_=json.NewEncoder(w).Encode(v)}
func outErr(w http.ResponseWriter,s int,c,m string){write(w,s,map[string]any{"error":map[string]string{"code":c,"message":m,"request_id":uuid.NewString()}})}
