ALTER TABLE projects
  ADD COLUMN IF NOT EXISTS workflow_state TEXT NOT NULL DEFAULT 'develop',
  ADD COLUMN IF NOT EXISTS final_iteration_id UUID REFERENCES iterations(id) ON DELETE RESTRICT;

ALTER TABLE projects DROP CONSTRAINT IF EXISTS projects_workflow_state_check;
ALTER TABLE projects ADD CONSTRAINT projects_workflow_state_check
  CHECK (workflow_state IN ('draft','explore','develop','ready_for_review','approved','final'));

CREATE TABLE IF NOT EXISTS project_approval_gates (
  project_id UUID PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  checklist JSONB NOT NULL DEFAULT '[]'::jsonb,
  override_checks JSONB NOT NULL DEFAULT '[]'::jsonb,
  override_reason TEXT,
  final_asset_id UUID REFERENCES assets(id) ON DELETE RESTRICT,
  review_requested_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  approved_by UUID REFERENCES users(id) ON DELETE SET NULL,
  finalized_at TIMESTAMPTZ,
  finalized_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS project_approval_gates_user_idx
  ON project_approval_gates(user_id, updated_at DESC);

ALTER TABLE export_records
  ADD COLUMN IF NOT EXISTS final_iteration_id UUID REFERENCES iterations(id) ON DELETE RESTRICT;

ALTER TABLE human_actions DROP CONSTRAINT IF EXISTS human_actions_type_check;
ALTER TABLE human_actions ADD CONSTRAINT human_actions_type_check CHECK (
  action_type IN (
    'IDEA_CREATED','SKETCH_IMPORTED','PROMPT_EDITED','PROMPT_APPROVED','REFERENCE_ADDED','REFERENCE_SELECTED',
    'VARIANT_SET_CREATED','VARIANT_SELECTED','VARIANT_REJECTED','VARIANT_FAVORITED','VARIANT_UNFAVORITED',
    'AI_RECOMMENDATION_REJECTED','COMPOSITION_CHANGED','COMPOSITION_MUTATION_ACCEPTED','COMPOSITION_APPROVED',
    'MATERIAL_SELECTED','TEXTURE_SELECTED','MANUAL_EDIT','APPROVED','EXPORT_CREATED',
    'APPROVAL_REQUESTED','PROJECT_APPROVED','PROJECT_FINALIZED','FINALIZE_OVERRIDE','PROJECT_REVISION_CREATED',
    'MATERIAL_CREATED','MATERIAL_UPDATED','MATERIAL_DELETED','TEXTURE_CREATED','TEXTURE_UPDATED','TEXTURE_DELETED',
    'STYLE_PROFILE_CREATED','STYLE_PROFILE_UPDATED','STYLE_PROFILE_APPLIED','ASSET_DNA_CREATED',
    'VISUAL_LANGUAGE_UPDATED','RIGHTS_UPDATED','DO_NOT_USE_UPDATED','LAYER_CREATED','LAYER_UPDATED',
    'LAYER_DELETED','MASK_CREATED','MANUAL_EDIT_CREATED','MANUAL_EDIT_APPLIED','MANUAL_EDIT_REJECTED',
    'CREATIVE_BRIEF_CREATED','CREATIVE_BRIEF_APPROVED'
  )
);
