ALTER TABLE variants DROP COLUMN IF EXISTS reject_reason_skipped;
ALTER TABLE variants DROP COLUMN IF EXISTS reject_severity;
ALTER TABLE variants DROP COLUMN IF EXISTS reject_comment;

DROP INDEX IF EXISTS variants_project_rejected_idx;

ALTER TABLE human_actions DROP CONSTRAINT IF EXISTS human_actions_type_check;
ALTER TABLE human_actions ADD CONSTRAINT human_actions_type_check CHECK (
  action_type IN (
    'IDEA_CREATED','SKETCH_IMPORTED','PROMPT_EDITED','PROMPT_APPROVED','REFERENCE_ADDED','REFERENCE_SELECTED',
    'VARIANT_SET_CREATED','VARIANT_SELECTED','VARIANT_REJECTED','VARIANT_FAVORITED','VARIANT_UNFAVORITED',
    'AI_RECOMMENDATION_REJECTED','COMPOSITION_CHANGED','COMPOSITION_MUTATION_ACCEPTED','MATERIAL_SELECTED',
    'TEXTURE_SELECTED','MANUAL_EDIT','APPROVED','EXPORT_CREATED','MATERIAL_CREATED','MATERIAL_UPDATED',
    'MATERIAL_DELETED','TEXTURE_CREATED','TEXTURE_UPDATED','TEXTURE_DELETED','STYLE_PROFILE_CREATED',
    'STYLE_PROFILE_UPDATED','STYLE_PROFILE_APPLIED','ASSET_DNA_CREATED','VISUAL_LANGUAGE_UPDATED',
    'RIGHTS_UPDATED','DO_NOT_USE_UPDATED','LAYER_CREATED','LAYER_UPDATED','LAYER_DELETED','MASK_CREATED',
    'MANUAL_EDIT_CREATED','MANUAL_EDIT_APPLIED','MANUAL_EDIT_REJECTED'
  )
);
