DROP TABLE IF EXISTS idempotency_requests;
ALTER TABLE human_actions DROP CONSTRAINT IF EXISTS human_actions_type_check;
ALTER TABLE human_actions ADD CONSTRAINT human_actions_type_check CHECK (
  action_type IN (
    'IDEA_CREATED','PROMPT_EDITED','PROMPT_APPROVED','REFERENCE_ADDED','REFERENCE_SELECTED',
    'VARIANT_SELECTED','VARIANT_REJECTED','AI_RECOMMENDATION_REJECTED','COMPOSITION_CHANGED',
    'MATERIAL_SELECTED','TEXTURE_SELECTED','MANUAL_EDIT','APPROVED','EXPORT_CREATED'
  )
);
DROP TABLE IF EXISTS library_items;
DROP TABLE IF EXISTS composition_mutations;
DROP TABLE IF EXISTS composition_specs;
DROP TABLE IF EXISTS export_records;
DROP TABLE IF EXISTS similarity_checks;
