package assets

import (
 "bytes"
 "encoding/json"
 "errors"
 "fmt"
 "io"
 "net/http"
 "path/filepath"
 "strconv"
	"strings"
 "time"
 "github.com/google/uuid"
 "github.com/oleg3190/Web-studio-img/backend/internal/auth"
 "github.com/oleg3190/Web-studio-img/backend/internal/events"
 "github.com/oleg3190/Web-studio-img/backend/internal/provenance"
 "github.com/oleg3190/Web-studio-img/backend/internal/storage"
)

type UploadHandler struct{store *Store;processor *Processor;storage storage.StorageProvider;events *events.Store;provenance *provenance.Store}
func NewUploadHandler(store *Store,processor *Processor,storageProvider storage.StorageProvider,ev *events.Store,pv *provenance.Store)(*UploadHandler,error){if store==nil||processor==nil{return nil,errors.New("asset upload handler requires store and processor")};return &UploadHandler{store:store,processor:processor,storage:storageProvider,events:ev,provenance:pv},nil}
func(h *UploadHandler)Register(mux *http.ServeMux){mux.HandleFunc("POST /api/v1/projects/{project_id}/assets",h.multipart);mux.HandleFunc("POST /api/v1/projects/{project_id}/assets/uploads",h.initUpload);mux.HandleFunc("PUT /api/v1/projects/{project_id}/assets/{asset_id}/parts/{part_number}",h.part);mux.HandleFunc("POST /api/v1/projects/{project_id}/assets/{asset_id}/complete",h.complete);mux.HandleFunc("GET /api/v1/projects/{project_id}/assets/{asset_id}",h.get);mux.HandleFunc("GET /api/v1/projects/{project_id}/assets/{asset_id}/download-url",h.downloadURL)}
func(h *UploadHandler)multipart(w http.ResponseWriter,r *http.Request){u,ok:=uploadUserID(r);if !ok{uploadErr(w,401,"unauthorized","authentication required");return};if h.storage==nil{uploadErr(w,503,"storage_unavailable","object storage is not configured");return};pid,err:=uuid.Parse(r.PathValue("project_id"));if err!=nil{uploadErr(w,400,"invalid_project_id","invalid project id");return};if err:=r.ParseMultipartForm(MaxAssetSize);err!=nil{uploadErr(w,400,"invalid_multipart","invalid multipart upload");return};file,header,err:=r.FormFile("file");if err!=nil{uploadErr(w,400,"file_required","multipart field file is required");return};defer file.Close();ext:=strings.ToLower(filepath.Ext(header.Filename))
	if ext!=".jpg" && ext!=".jpeg" && ext!=".png" { uploadErr(w,400,"invalid_extension","only .jpg, .jpeg and .png files are supported"); return }
	data,err:=io.ReadAll(io.LimitReader(file,MaxAssetSize+1));if err!=nil{uploadErr(w,400,"file_read_failed","could not read file");return};if int64(len(data))>MaxAssetSize||header.Size>MaxAssetSize{uploadErr(w,413,"file_too_large","asset exceeds size limit");return};item,err:=h.processor.ProcessUpload(r.Context(),u,pid,data,header.Header.Get("Content-Type"));if err!=nil{uploadErr(w,400,"asset_upload_failed",err.Error());return};h.emit(r,u,pid,item.ID,"asset_created",map[string]any{"type":item.Type,"storage_key":item.StorageKey,"checksum":item.Checksum});uploadJSON(w,201,item)}
func(h *UploadHandler)initUpload(w http.ResponseWriter,r *http.Request){u,ok:=uploadUserID(r);if !ok{uploadErr(w,401,"unauthorized","authentication required");return};pid,err:=uuid.Parse(r.PathValue("project_id"));if err!=nil{uploadErr(w,400,"invalid_project_id","invalid project id");return};var in struct{MIMEType string `json:"mime_type"`;Size int64 `json:"size"`};if err:=decodeUploadJSON(r,&in);err!=nil{uploadErr(w,400,"invalid_request","invalid upload metadata");return};item,err:=h.store.CreatePendingUpload(r.Context(),u,pid,in.MIMEType,in.Size);if err!=nil{uploadErr(w,400,"invalid_upload","could not initialize upload");return};if h.storage==nil{_ = h.store.MarkOrphaned(r.Context(),u,item.ID);uploadErr(w,503,"storage_unavailable","object storage is not configured");return};url,err:=h.storage.PresignPut(r.Context(),item.StorageKey,10*time.Minute,item.MIMEType);if err!=nil{_ = h.store.MarkOrphaned(r.Context(),u,item.ID);uploadErr(w,503,"upload_url_failed","could not create signed upload URL");return};uploadJSON(w,201,map[string]any{"upload_id":item.ID,"asset":item,"upload_url":url.URL,"expires_at":url.ExpiresAt})}
func(h *UploadHandler)part(w http.ResponseWriter,r *http.Request){u,ok:=uploadUserID(r);if !ok{uploadErr(w,401,"unauthorized","authentication required");return};if h.storage==nil{uploadErr(w,503,"storage_unavailable","object storage is not configured");return};pid,err:=uuid.Parse(r.PathValue("project_id"));if err!=nil{uploadErr(w,400,"invalid_project_id","invalid project id");return};id,err:=uuid.Parse(r.PathValue("asset_id"));if err!=nil{uploadErr(w,400,"invalid_asset_id","invalid asset id");return};n,err:=strconv.Atoi(r.PathValue("part_number"));if err!=nil||n<0||n>10000{uploadErr(w,400,"invalid_part_number","invalid part number");return};data,err:=io.ReadAll(http.MaxBytesReader(w,r.Body,MaxUploadPartSize));if err!=nil||int64(len(data))>MaxUploadPartSize{uploadErr(w,413,"part_too_large","upload part exceeds 2 MiB");return};start,end,total,err:=parseRange(r.Header.Get("Content-Range"));if err!=nil||start/MaxUploadPartSize!=int64(n)||end-start+1!=int64(len(data))||total>MaxAssetSize{uploadErr(w,400,"invalid_content_range","Content-Range does not match part");return};key:=fmt.Sprintf("users/%s/projects/%s/assets/%s/parts/%d",u,pid,id,n);if err:=h.storage.Put(r.Context(),key,bytes.NewReader(data),int64(len(data)),storage.PutOptions{ContentType:"application/octet-stream"});err!=nil{uploadErr(w,502,"part_upload_failed","could not store upload part");return};if err:=h.store.AddUploadPart(r.Context(),u,pid,id,n,key,int64(len(data)));err!=nil{_ = h.storage.Delete(r.Context(),key);uploadErr(w,400,"part_rejected","upload part rejected");return};uploadJSON(w,200,map[string]any{"asset_id":id,"part_number":n,"size":len(data),"total":total})}
func(h *UploadHandler)complete(w http.ResponseWriter,r *http.Request){u,ok:=uploadUserID(r);if !ok{uploadErr(w,401,"unauthorized","authentication required");return};if h.storage==nil{uploadErr(w,503,"storage_unavailable","object storage is not configured");return};pid,err:=uuid.Parse(r.PathValue("project_id"));if err!=nil{uploadErr(w,400,"invalid_project_id","invalid project id");return};id,err:=uuid.Parse(r.PathValue("asset_id"));if err!=nil{uploadErr(w,400,"invalid_asset_id","invalid asset id");return};item,err:=h.store.GetOwned(r.Context(),u,pid,id);if err!=nil{uploadErr(w,404,"asset_not_found","asset not found");return};parts,err:=h.store.ListUploadParts(r.Context(),u,pid,id);if err!=nil{uploadErr(w,400,"upload_parts_failed","could not list upload parts");return};if len(parts)>0{var buf bytes.Buffer;var total int64;for i,p:=range parts{if p.PartNumber!=i{uploadErr(w,400,"parts_incomplete","parts must be contiguous from 0");return};obj,_,err:=h.storage.Get(r.Context(),p.StorageKey);if err!=nil{uploadErr(w,502,"part_read_failed","could not read upload part");return};n,err:=io.Copy(&buf,obj);_=obj.Close();if err!=nil{uploadErr(w,502,"part_read_failed","could not read upload part");return};total+=n};if total!=item.Size{uploadErr(w,400,"size_mismatch","assembled upload size does not match declared size");return};if err:=h.storage.Put(r.Context(),item.StorageKey,bytes.NewReader(buf.Bytes()),total,storage.PutOptions{ContentType:item.MIMEType});err!=nil{uploadErr(w,502,"assemble_failed","could not assemble upload");return};for _,p:=range parts{_=h.storage.Delete(r.Context(),p.StorageKey)};_=h.store.DeleteUploadParts(r.Context(),id)};final,err:=h.processor.ProcessPendingUpload(r.Context(),u,pid,id);if err!=nil{uploadErr(w,400,"asset_finalize_failed",err.Error());return};h.emit(r,u,pid,final.ID,"asset_created",map[string]any{"type":final.Type,"storage_key":final.StorageKey,"checksum":final.Checksum});uploadJSON(w,200,final)}
func(h *UploadHandler)get(w http.ResponseWriter,r *http.Request){u,ok:=uploadUserID(r);if !ok{uploadErr(w,401,"unauthorized","authentication required");return};pid,err:=uuid.Parse(r.PathValue("project_id"));if err!=nil{uploadErr(w,400,"invalid_project_id","invalid project id");return};id,err:=uuid.Parse(r.PathValue("asset_id"));if err!=nil{uploadErr(w,400,"invalid_asset_id","invalid asset id");return};item,err:=h.store.GetOwned(r.Context(),u,pid,id);if err!=nil{uploadErr(w,404,"asset_not_found","asset not found");return};uploadJSON(w,200,item)}
func(h *UploadHandler)downloadURL(w http.ResponseWriter,r *http.Request){u,ok:=uploadUserID(r);if !ok{uploadErr(w,401,"unauthorized","authentication required");return};if h.storage==nil{uploadErr(w,503,"storage_unavailable","object storage is not configured");return};pid,err:=uuid.Parse(r.PathValue("project_id"));if err!=nil{uploadErr(w,400,"invalid_project_id","invalid project id");return};id,err:=uuid.Parse(r.PathValue("asset_id"));if err!=nil{uploadErr(w,400,"invalid_asset_id","invalid asset id");return};item,err:=h.store.GetOwned(r.Context(),u,pid,id);if err!=nil{uploadErr(w,404,"asset_not_found","asset not found");return};url,err:=h.storage.PresignGet(r.Context(),item.StorageKey,10*time.Minute);if err!=nil{uploadErr(w,503,"download_url_failed","could not create signed download URL");return};uploadJSON(w,200,map[string]any{"asset_id":id,"url":url.URL,"expires_at":url.ExpiresAt})}
func(h *UploadHandler)emit(r *http.Request,u,pid,id uuid.UUID,action string,payload map[string]any){if h.events!=nil{_,_=h.events.Append(r.Context(),u,pid,"asset.created","asset",id,payload)};if h.provenance!=nil{_,_=h.provenance.Append(r.Context(),provenance.Event{UserID:u,ProjectID:pid,EntityType:"asset",EntityID:id,Action:action,Payload:payload});if h.events!=nil{_,_=h.events.Append(r.Context(),u,pid,"provenance.updated","asset",id,map[string]any{"action":action})}}}
func uploadUserID(r *http.Request)(uuid.UUID,bool){p,ok:=auth.PrincipalFromContext(r.Context());if !ok{return uuid.Nil,false};return p.UserID,true}
func decodeUploadJSON(r *http.Request,v any)error{d:=json.NewDecoder(io.LimitReader(r.Body,1<<20));d.DisallowUnknownFields();if err:=d.Decode(v);err!=nil{return err};var extra any;if err:=d.Decode(&extra);err!=io.EOF{return errors.New("multiple JSON values")};return nil}
func uploadJSON(w http.ResponseWriter,status int,v any){w.Header().Set("Content-Type","application/json");w.WriteHeader(status);_=json.NewEncoder(w).Encode(v)}
func uploadErr(w http.ResponseWriter,status int,code,msg string){uploadJSON(w,status,map[string]any{"error":map[string]string{"code":code,"message":msg,"request_id":uuid.NewString()}})}
func parseRange(value string)(int64,int64,int64,error){if len(value)<7||value[:6]!="bytes "{return 0,0,0,errors.New("invalid Content-Range")};parts:=strings.Split(value[6:],"/");if len(parts)!=2{return 0,0,0,errors.New("invalid Content-Range")};bounds:=strings.Split(parts[0],"-");if len(bounds)!=2{return 0,0,0,errors.New("invalid Content-Range")};start,e1:=strconv.ParseInt(bounds[0],10,64);end,e2:=strconv.ParseInt(bounds[1],10,64);total,e3:=strconv.ParseInt(parts[1],10,64);if e1!=nil||e2!=nil||e3!=nil||start<0||end<start||total<=0{return 0,0,0,errors.New("invalid Content-Range")};return start,end,total,nil}
